management/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('management.views',
	url(r'^$', 'index', name='dashboard_index'),
	url(r'^member_biro$', 'member_biro', name='member_biro'),
	url(r'^member_biro/new$', 'new_member_biro', name='new_member_biro'),
	url(r'^member_biro/delete/(?P<id>[0-9]+)$', 'delete_member_biro', name='delete_member_biro'),

	url(r'^profile$', 'profile', name='profile'),

	url(r'^data_leads$', 'data_leads', name='data_leads'),

	url(r'^paket_biro$', 'paket_biro', name='paket_biro'),
	url(r'^paket_biro/new$', 'new_paket_biro', name='new_paket_biro'),
	url(r'^paket_biro/edit/(?P<id>[0-9]+)$', 'edit_paket_biro', name='edit_paket_biro'),
	url(r'^paket_biro/delete/(?P<id>[0-9]+)$', 'delete_paket_biro', name='delete_paket_biro'),

	url(r'^paket_member$', 'paket_member', name='paket_member'),
	url(r'^paket_member/new$', 'new_paket_member', name='new_paket_member'),
	url(r'^paket_member/(?P<id>[0-9]+)$', 'show_paket_member', name='show_paket_member'),
	url(r'^paket_member/edit/(?P<id>[0-9]+)$', 'edit_paket_member', name='edit_paket_member'),
	url(r'^paket_member/delete/(?P<id>[0-9]+)$', 'delete_paket_member', name='delete_paket_member'),

	url(r'^paket_umroh$', 'paket_umroh', name='paket_umroh'),
	url(r'^paket_umroh/new$', 'new_paket_umroh', name='new_paket_umroh'),
	url(r'^paket_umroh/delete/(?P<id>[0-9]+)$', 'delete_paket_umroh', name='delete_paket_umroh'),

	url(r'^promosi_umroh$', 'promosi_umroh', name='promosi_umroh'),
	url(r'^promosi_umroh/new$', 'new_promosi_umroh', name='new_promosi_umroh'),

	url(r'^konfigurasi$', 'konfigurasi', name='konfigurasi'),

	url(r'^akses_halaman_biro$', 'akses_halaman_biro', name='akses_halaman_biro'),
	url(r'^akses_halaman_promo$', 'akses_halaman_promo', name='akses_halaman_promo'),

	url(r'^customer_services$', 'customer_services', name='customer_services'),
	url(r'^customer_services/new$', 'new_customer_services', name='new_customer_services'),
	url(r'^customer_services/(?P<id>[0-9]+)$', 'show_customer_services', name='show_customer_services'),
	url(r'^customer_services/edit/(?P<id>[0-9]+)$', 'edit_customer_services', name='edit_customer_services'),
	url(r'^customer_services/delete/(?P<id>[0-9]+)$', 'delete_customer_services', name='delete_customer_services'),
)

testing_db/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ikhram.views.home', name='home'),
    url(r'^$', 'ikhram.views.login', name='login'),
    url(r'^logout/$', 'ikhram.views.logout', name='logout'),
	url(r'^dashboard/', include('management.urls')),   
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT })
)

management/models.py
from django.db import models

from ikhram.models import *
from django.contrib.auth.models import User
from django.conf import settings
from django.template.defaultfilters import slugify

from datetime import *

# Create your models here.

class PlanPackages(models.Model):

	name = models.CharField(max_length=255, null=True)
	logo = models.BooleanField(default=False)
	phone = models.BooleanField(default=False)
	detailed_visitor_data = models.BooleanField(default=False)
	promo_unlimited = models.BooleanField(default=False)
	warranty_visitor_per_year = models.BooleanField(default=False)
	commission = models.CharField(max_length=255)
	minimal_discount = models.FloatField(default=0.0)
	cost_per_year = models.IntegerField(max_length=255)
	slug = models.SlugField(editable=False)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = 'plan_packages'
		verbose_name_plural = "Pilihan Paket"

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		if self.created_at == None:
			self.created_at = datetime.now()
		self.updated_at = datetime.now()
		self.slug = slugify(self.name)
		super(PlanPackages, self).save(*args, **kwargs)

class BiroMembers(models.Model):
	agent = models.ForeignKey(Agents)
	user = models.ForeignKey(User)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = 'biro_members'
		verbose_name_plural = "Member Biro"

	def __unicode__(self):
		return self.user.username

	def save(self, *args, **kwargs):
		if self.created_at == None:
			self.created_at = datetime.now()
		self.updated_at = datetime.now()
		super(BiroMembers, self).save(*args, **kwargs)


class BiroPackages(models.Model):

	FORMAT_DATES = ['%Y-%m-%d', '%d-%m-%Y']

	biro_member = models.ForeignKey(BiroMembers)
	plan_package = models.ForeignKey(PlanPackages)
	expired = models.DateField(null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = 'biro_packages'
		verbose_name_plural = "Paket Biro"

	def __unicode__(self):
		return self.biro_member.agent.name

	def save(self, *args, **kwargs):
		if self.created_at == None:
			self.created_at = datetime.now()
		self.updated_at = datetime.now()
		super(BiroPackages, self).save(*args, **kwargs)

class TemplateTermsAgents(models.Model):

	agent = models.ForeignKey(Agents)
	name = models.CharField(max_length=255, blank=True)
	name_folder = models.CharField(max_length=255, blank=True)
	slug = models.SlugField(editable=False)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = 'template_terms_agents'
		verbose_name_plural = "Template Syarat dan Ketentuan"

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		if self.created_at == None:
			self.created_at = datetime.now()
		self.updated_at = datetime.now()
		self.slug = slugify(self.name)
		super(TemplateTermsAgents, self).save(*args, **kwargs)

class ConfigurationPackets(models.Model):

	agent = models.ForeignKey(Agents)
	last_allowed_book = models.CharField(max_length=255, null=True)
	dp_idr = models.CharField(max_length=255, null=True)
	dp_dollar = models.CharField(max_length=255, null=True)
	terms_condition = models.TextField(null=True)
	included_facility = models.TextField(null=True)
	excluded_facility = models.TextField(null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = 'configuration_packets'
		verbose_name_plural = "Konfigurasi Paket"

	def __unicode__(self):
		return self.agent.name

	def save(self, *args, **kwargs):
		if self.created_at == None:
			self.created_at = datetime.now()
		self.updated_at = datetime.now()
		super(ConfigurationPackets, self).save(*args, **kwargs)

class CustomerServiceAgents(models.Model):

	agent = models.ForeignKey(Agents)
	name = models.CharField(max_length=255, null=True)
	photo = models.ImageField(upload_to='uploads/customer_service', null=True)
	phone = models.CharField(max_length=255, null=True)
	bbm = models.CharField(max_length=255, null=True)
	wa = models.CharField(max_length=255, null=True)
	email = models.CharField(max_length=255, null=True)
	phone_office = models.CharField(max_length=255, null=True)
	slug = models.SlugField(editable=False)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = 'customer_service_agents'
		verbose_name_plural = "Customer Service Biro"

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		if self.created_at == None:
			self.created_at = datetime.now()
		self.updated_at = datetime.now()
		self.slug = slugify(self.name)
		super(CustomerServiceAgents, self).save(*args, **kwargs)

templates/akses_halaman_biro.html
{% extends "base.html" %}

{% block content %}
<!-- BEGIN PAGE HEADER-->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"> Akses Halaman Biro
</h3>
<!-- END PAGE TITLE-->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{% url 'dashboard_index' %}">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Akses Halaman Biro</span>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    &nbsp; </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form id="akses_halaman_biro" action="{% url 'akses_halaman_biro' %}" class="form-horizontal" method="GET">
                    <div class="form-body">
                        <div class="alert alert-danger display-hide">
                            <button class="close" data-close="alert"></button> You have some form errors. Please check below. </div>
                        <div class="alert alert-success display-hide">
                            <button class="close" data-close="alert"></button> Your form validation is successful! </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Tanggal Mulai</label>
                            <div class="col-md-4">
                                <div class="input-group date date-picker" data-date-format="dd-mm-yyyy">
                                    <input type="text" class="form-control" id="start_date" readonly="" name="start_date" {% if start_date %}value="{{ start_date }}" {% endif %}>
                                    <span class="input-group-btn">
                                        <button class="btn default" type="button">
                                            <i class="fa fa-calendar"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label">Tanggal Berakhir</label>
                            <div class="col-md-4">
                                <div class="input-group date date-picker" data-date-format="dd-mm-yyyy">
                                    <input type="text" class="form-control" id="end_date" readonly="" name="end_date" {% if end_date %}value="{{ end_date }}" {% endif %}>
                                    <span class="input-group-btn">
                                        <button class="btn default" type="button">
                                            <i class="fa fa-calendar"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn btn-circle green">Submit</button>
                                <!-- <a href="{% url 'member_biro' %}" class="btn btn-circle grey-salsa btn-outline">Cancel</a> -->
                            </div>
                        </div>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>

<div class="row" id="chart_biro" {% if start_date and end_date %}style="display: block;"{% else %}style="display: none;"{% endif %}>
    <div class="col-md-12">
        <!-- BEGIN ROW -->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN CHART PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bar-chart font-green-haze"></i>
                            <span class="caption-subject bold uppercase font-green-haze"> Akses Halaman Biro</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div id="menu_akses_biro" class="chart" style="height: 500px;"> </div>
                    </div>
                </div>
                <!-- END CHART PORTLET-->
            </div>
        </div>
        <!-- END ROW -->
        <!-- BEGIN ROW -->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN CHART PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bar-chart font-green-haze"></i>
                            <span class="caption-subject bold uppercase font-green-haze"> Detail Akses Halaman Biro</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover order-column" id="withoutCheckbox">
                            <thead>
                                <tr>
                                    <th> Nama Pengunjung </th>
                                    <th> Lokasi </th>
                                    <th> Tanggal Akses</th>
                                    <!-- <th> Lihat Detail </th> -->
                                </tr>
                            </thead>
                            <tbody>
                                {% for cp in detail_access_agents %}
                                <tr class="odd gradeX">
                                    <td>{{ cp.web_user_name }}</td>
                                    <td>{{ cp.web_user_location }}</td>
                                    <td>{{ cp.created_at|date:"d M Y" }}</td>
                                    <!-- <td>
                                        <a class="btn btn-xs btn-info" href="javascript:;">
                                            <i class="ace-icon fa fa-eye bigger-120"></i>
                                        </a>
                                    </td> -->
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- END CHART PORTLET-->
            </div>
        </div>
        <!-- END ROW -->
    </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function(){
        var chart_access_agents = {{ chart_access_agents|safe }}
        var chart3 = AmCharts.makeChart("menu_akses_biro", {
            "type": "serial",
            "theme": "light",

            "fontFamily": 'Open Sans',            
            "color":    '#888888',
            
            "pathToImages": "/media/metronic/global/plugins/amcharts/amcharts/images/",

            "dataProvider": chart_access_agents,
            "balloon": {
                "cornerRadius": 6
            },
            "valueAxes": [{
                "position": "left"
            }],
            "startDuration": 1,
            "graphs": [{
                "bullet": "square",
                "bulletBorderAlpha": 1,
                "bulletBorderThickness": 1,
                "fillAlphas": 0.3,
                "fillColorsField": "lineColor",
                "legendValueText": "[[value]]",
                "lineColorField": "lineColor",
                "title": "duration",
                "valueField": "duration"
            }],
            "chartScrollbar": {},
            "chartCursor": {
                "categoryBalloonDateFormat": "YYYY MMM DD",
                "cursorAlpha": 0,
                "zoomable": false
            },
            "dataDateFormat": "YYYY-MM-DD",
            "categoryField": "date"
        });

        $('#menu_akses_biro').closest('.portlet').find('.fullscreen').click(function() {
            chart3.invalidateSize();
        });

    })
</script>
{% endblock %}

templates/form_customer_services.html
{% extends "base.html" %}

{% block content %}
<!-- BEGIN PAGE HEADER-->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"> Customer Services
    <small>{{ action }} Customer Services</small>
</h3>
<!-- END PAGE TITLE-->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{% url 'dashboard_index' %}">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{% url 'customer_services' %}">Customer Services</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>{{ action }} Customer Services</span>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class=" icon-layers font-red"></i>
                    <span class="caption-subject font-red bold uppercase"> Form Customer Services
                    </span>
                </div>
            </div>
            <div class="portlet-body form">
                <form class="form-horizontal" action="{% if action == 'New' %}{% url 'new_customer_services' %}{% else %}{% url 'edit_customer_services' id=cs.id %}{% endif %}" id="{% if action == 'New' %}form_cs{% else %}edit_form_cs{% endif %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="form-body">
                        <div class="alert alert-danger display-none">
                            <button class="close" data-dismiss="alert"></button> You have some form errors. Please check below. </div>
                        <div class="alert alert-success display-none">
                            <button class="close" data-dismiss="alert"></button> Your form validation is successful! </div>
                        {% if request.user.is_staff %}
                        <div class="form-group">
                            <label class="control-label col-md-3">Biro
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-4">
                                <select id="agent_id" name="agent_id" class="form-control select2me">
                                    <option value="">-- Pilih Biro --</option>
                                    {% for i in agents %}
                                    <option value="{{ i.id }}">{{ i.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        {% else %}
                        <input type="hidden" id="agent_id" name="agent_id" value="{{ request.user.biromembers_set.all.0.agent_id }}">
                        {% endif %}
                        <div class="form-group">
                            <label class="control-label col-md-3">Photo
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-4">
                                <input type="file" class="form-control" id="photo" name="photo" />
                                {% if action == "Edit" %}
                                <p class="form-control-static"> <img src="{{ MEDIA_URL }}{{ cs.photo }}" width="100"> </p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Nama
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id="nama" name="nama" value="{{ cs.name }}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Email
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id="email" name="email" value="{{ cs.email }}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Telepon
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="phone" name="phone" value="{{ cs.phone }}" />
                                <span class="help-block"> Gunakan tanda pemisah ',' (koma) jika lebih dari satu </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">BBM
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id="bbm" name="bbm" value="{{ cs.bbm }}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Whatsapp
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id="wa" name="wa" value="{{ cs.wa }}" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Telepon Kantor
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id="phone_office" name="phone_office" value="{{ cs.phone_office }}" />
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn btn-circle green">Submit</button>
                                <a href="{% url 'customer_services' %}" class="btn btn-circle grey-salsa btn-outline">Cancel</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/form_konfigurasi.html
{% extends "base.html" %}

{% block content %}
<style type="text/css">
.nicehide {
    display: block !important;
    position: absolute; /*Keep the object's original position*/
    width: 0 !important; /*It should be 0 width. Otherwise the object seems underneath of the editor */
    z-index: -1; /*Send the object to the bottom layer*/
}
</style>
<!-- BEGIN PAGE HEADER-->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"> Konfigurasi
    <small>{{ action }} Konfigurasi</small>
</h3>
<!-- END PAGE TITLE-->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{% url 'dashboard_index' %}">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>{{ action }} Konfigurasi</span>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Form {{ action }} Konfigurasi </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form id="konfigurasi" action="{% url 'konfigurasi' %}" class="form-horizontal" method="POST">{% csrf_token %}
                    <div class="form-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} display-none" style="display: block;">
                                    <button class="close" data-dismiss="alert"></button> {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="alert alert-danger display-hide">
                            <button class="close" data-close="alert"></button> You have some form errors. Please check below. </div>
                        <div class="alert alert-success display-hide">
                            <button class="close" data-close="alert"></button> Your form validation is successful! </div>
                        <input type="hidden" id="agent_id" name="agent_id" value="{{ request.user.biromembers_set.all.0.agent_id }}" >
                        <div class="form-group">
                            <label class="col-md-3 control-label">Batas Booking (hari) <span class="required"> * </span></label>
                            <div class="col-md-4">
                                <input type="text" id="last_allowed_book" name="last_allowed_book" class="form-control" value="{{ cp.last_allowed_book }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Uang DP IDR <span class="required"> * </span></label>
                            <div class="col-md-4">
                                <input type="text" id="dp_idr" name="dp_idr" class="form-control" value="{{ cp.dp_idr }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Uang DP Dollar <span class="required"> * </span></label>
                            <div class="col-md-4">
                                <input type="text" id="dp_dollar" name="dp_dollar" class="form-control" value="{{ cp.dp_dollar }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Fasilitas Yang Termasuk
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-9">
                                <textarea class="wysihtmlIncluded form-control" rows="6" id="included_facility" name="included_facility" data-error-container="#included_facility_error">{{ cp.included_facility }}</textarea>
                                <div id="included_facility_error"> </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Fasilitas Yang Tidak Termasuk
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-9">
                                <textarea class="wysihtmlExcluded form-control" rows="6" id="excluded_facility" name="excluded_facility" data-error-container="#excluded_facility_error">{{ cp.excluded_facility }}</textarea>
                                <div id="excluded_facility_error"> </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Syarat dan Ketentuan
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-9">
                                <textarea class="wysihtmlTermsCondition form-control" rows="6" id="terms_condition" name="terms_condition" data-error-container="#terms_condition_error">{{ cp.terms_condition }}</textarea>
                                <div id="terms_condition_error"> </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn btn-circle green">Submit</button>
                                <!-- <a href="{% url 'member_biro' %}" class="btn btn-circle grey-salsa btn-outline">Cancel</a> -->
                            </div>
                        </div>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/home.html
HELLO WORLD !